### ISSUE TITLE
Login error

### ISSUE THREAD

**Issue by morpheusoliver** [chrisc123/jebao_aqua-homeassistant#13]
I'm trying to run the integration but i always get credential error, even after veryfing with the app and creating a new password, seems like the 'GET' endpoint has been removed.

![image](https://github.com/user-attachments/assets/652b73ee-9312-472f-b5ca-0f5a382df941)

**Comment by chrisc123** [comment]
Hi - are you based in Europe or somewhere else in the world? If you're outside Europe you may need to update the API endpoints in const.py to the US version and also try changing the GIZWITS_APP_ID to 6c9b7c67e81345b5a5b6817f31f82ac8 (See https://github.com/chrisc123/jebao_aqua-homeassistant/issues/11)

**Comment by EvoSems** [comment]
I think that APPID isn't working correctly anymore, I'm have issues also. Do we have a list of APP ID?

```
HTTP 400 Bad Request
Content-Type: application/json
Vary: Accept
Allow: GET, HEAD, OPTIONS

{
    "error_message": "appid invalid!",
    "error_code": 9003,
    "detail_message": null
}
```

**Comment by morpheusoliver** [comment]
The app 6c9b7c67e81345b5a5b6817f31f82ac8  + usa urls did the trick, thanks!
